// AUTO-GENERATED by scripts/generate-email-template-index.mjs.
// Add or remove template files in lib/emailTemplates and restart/build the app.
// Do not edit this file manually.

import template0 from "./testNewsletter";

const templates = [template0];

export function getEmailTemplates() {
  return templates;
}

export function getEmailTemplate(id) {
  return templates.find((template) => template.id === id) || null;
}
